# Generated by Django 2.0 on 2018-08-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_id', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(default='', max_length=64)),
                ('photo', models.URLField(default=None)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
