# Generated by Django 2.0 on 2018-08-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
